# -*- coding: utf-8 -*-
"""Simulacion_Energias_MAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uV4fPVzWcMAWfmgkxqu8XBqql0lNodEu
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

# Título y explicaciones (edita aquí tus conceptos)
st.title("Simulación Interactiva de Energías en el MAS")
st.markdown("""
### Conceptos Básicos del MAS
- **Energía Potencial (EP)**: Energía almacenada por deformación del resorte. Fórmula: EP = (1/2) k x². Máxima en los extremos.
- **Energía Cinética (EC)**: Energía del movimiento. Fórmula: EC = (1/2) m v². Máxima en el equilibrio.
- **Energía Total (ET)**: EP + EC, constante en un sistema ideal (conservación de energía).

**Instrucciones**: Mueve los sliders y haz clic en "¡Simular!" para ver el gráfico.
""")

# Sliders
A = st.slider("Amplitud (A) en metros", min_value=0.1, max_value=5.0, value=1.0, step=0.1)
m = st.slider("Masa (m) en kg", min_value=0.1, max_value=5.0, value=1.0, step=0.1)
k = st.slider("Constante del resorte (k) en N/m", min_value=0.1, max_value=10.0, value=1.0, step=0.1)
t_final = st.slider("Tiempo final en segundos", min_value=5, max_value=50, value=20, step=5)

# Botón
if st.button("¡Simular!"):
    omega = np.sqrt(k / m)
    t = np.linspace(0, t_final, 1000)
    x = A * np.cos(omega * t)
    v = -A * omega * np.sin(omega * t)
    EP = 0.5 * k * x**2
    EC = 0.5 * m * v**2
    ET = EP + EC

    fig, ax = plt.subplots(figsize=(10, 6))
    ax.plot(t, EP, label='Energía Potencial (EP)', color='blue')
    ax.plot(t, EC, label='Energía Cinética (EC)', color='green')
    ax.plot(t, ET, label='Energía Total (ET)', color='red', linestyle='--')
    ax.set_xlabel('Tiempo (s)')
    ax.set_ylabel('Energía (J)')
    ax.set_title('Energías en el MAS')
    ax.legend()
    ax.grid(True)
    st.pyplot(fig)